---
title: "SunsVizOnly"
author: "Adam Rees"
date: "3/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(rvest)
library(dplyr)
require(XML)
require(RCurl)
require(stringr)
require(png)
library(XML)
library(tidyr)
library(MASS)
library(sp)
library(gstat)


library(rapportools)

```

5958
#First, get the whole dataset up and running
```{r}
gameData <- read.csv("~/Desktop/Thesis/ThesisBasketball/totalSunsGames.csv")
gameData <- gameData %>% filter(gameData$point != 1)

```

#Run *if* you are doing a randomization test for one player
```{r}

```


#Get the rest of the dataset up and running
```{r}
gameData$pointsPerShot <- NULL
gameData$X_LOC <- NULL
gameData$Y_LOC <- NULL


for(i in 1:nrow(gameData)){
  gameData$X_LOC[i] <- -1 * as.double(gameData$baseline[i] * 500)
  gameData$Y_LOC[i] <- as.double(gameData$sideline[i] * 940)
  gameData$pointsPerShot[i] <- as.double(gameData$makes[i] * gameData$point[i])

}

#If you just want shots at the basket
gameData <- gameData %>% filter(gameData$X_LOC >= -50, gameData$X_LOC <= 50, gameData$Y_LOC <= 50, gameData$Y_LOC >= -11)


#The following code is so that we can get n, ppsAve for each location
nvalues <- gameData %>% group_by(X_LOC, Y_LOC) %>% count() 
dupShots <- gameData %>% left_join(nvalues)

sumShots <- dupShots %>% group_by(X_LOC, Y_LOC) %>% mutate(pps = sum(pointsPerShot))

#Now you have the pps for each location
gameData$n <- sumShots$n
gameData$ppsAve <- sumShots$pps/sumShots$n

# All of the different locations we will be dealing with
xLocs <- sort(unique(gameData$X_LOC))
yLocs <- sort(unique(gameData$Y_LOC))


gameData <- gameData %>% arrange(X_LOC, Y_LOC)
gameData <- gameData %>% distinct(X_LOC, Y_LOC, .keep_all = TRUE) %>% arrange(X_LOC, Y_LOC)


```

#The functions to run the code
```{r}

#put the if .. 
rbf.k <- function(x,y,sigma)
  return(exp(-1/(2*sigma^2)*(sum((x-y)^2))))


covGen <- function(xLoc, yLoc, lam) {
  # Evaluates mean and covariance of GP at grid of points on [0,1]
  # Inputs:
  # x, y: input and output values of data set
  # lam: smoothing parameter in RBF kernel
  # sig: error standard deviation of y
  # design: grid of points to evaluate the GP
  # Returns:
  # mean=posterior mean, vars=posterior variance, and design=evaluation points
  n <- length(xLoc) * length(yLoc)
  Sigma <- matrix(0, nrow = n, ncol = n)
  all <- matrix(0, nrow = n, ncol = 2)
  k <- 1
  
  for (i in 1:length(xLoc)) {
    for (j in 1:length(yLoc)) {
    all[k, ] <- c(xLoc[i], yLoc[j])
    k <- k + 1
    }
  }
  
  all[i,][2]

  for (i in 1:nrow(Sigma)) {
    for (j in i:nrow(Sigma)){
      #If first shot is a three 
      if ((all[i,][2] < 100 & (all[i,][1] >220 | all[i,][1] < -220)) | (all[i,][2]>=100 & (sqrt(all[i,][2]^2 + all[i,][1]^2) > 237))){
        #second shot is a three
        if((all[j,][2] < 100 & (all[j,][1] >220 | all[j,][1] < -220)) | (all[j,][2]>=100 & (sqrt(all[j,][2]^2 + all[j,][1]^2) > 237))){
          Sigma[i, j] <- rbf.k(all[i,], all[j,], lam) -> Sigma[j, i]
        }
        #second shot is a two
        else{
          Sigma[i, j] <- 0 -> Sigma[j, i]
          
        }
      }
      #if first shot is a two
      else{
        #second shot is a three
        if((all[j,][2] < 100 & (all[j,][1] >220 | all[j,][1] < -220)) | (all[j,][2]>=100 & (sqrt(all[j,][2]^2 + all[j,][1]^2) > 237))){
          Sigma[i, j] <- 0 -> Sigma[j, i]
          
        }#second shot is a two
        else{
          Sigma[i, j] <- rbf.k(all[i,], all[j,], lam) -> Sigma[j, i]
        }
        
      }
    }
  }
    return(Sigma)
  }

#Find the pps and the sigma at every location
yVals <- function(xLocs, yLocs, data) {
  counter <- 1
  tempY <- c()
  tempSig <- c()

for (i in 1:length(xLocs)) {
  for (j in 1:length(yLocs)) {
    if (!is.na(data$X_LOC[counter]) &
        data$X_LOC[counter] == xLocs[i] & data$Y_LOC[counter] == yLocs[j]) {
      tempY <- c(tempY, data$ppsAve[counter])
      tempSig <- c(tempSig, 1 / sqrt(data$n[counter]))
      counter <- counter + 1
    } else{
      tempY <- c(tempY, 0)
      tempSig <- c(tempSig, 1000)
    }
  }
}
  
  finalVector <- data.frame(tempY, tempSig)
  return(finalVector)
}

#Another function doing the last stuff of greg

#sig shows up, how many shots at the grid point 
finalFunction <- function(Sigma, y, sig){
  

  # sig would be an n length vector
  inv <- Sigma%*%solve(Sigma+diag(sig^2))
  
  #y would be, at every grid point what is the average grid point
  mean <- inv%*%y
  cov <- Sigma-inv%*%Sigma
  vars <- diag(cov)
  return(list(mean=mean, vars=vars))
}


```

```{r}
a <- covGen(grid.a, grid.b, lam = 47)
```


#Estimate visualizations
```{r}

grid.a <- xLocs
grid.b <- yLocs

b <- yVals(grid.a, grid.b, gameData)
c <- finalFunction(a, b$tempY, b$tempSig)


k <- 1
mean.fit <- matrix(0, nrow = length(grid.a), ncol = length(grid.b))
for (i in 1:length(grid.a)) {
  for (j in 1:length(grid.b)) {
    mean.fit[i, j] <- c$mean[k]
    k <- k + 1
  }
}



plot(gameData$X_LOC, gameData$Y_LOC)


#Show the findings!
library(fields)
colorTable<- designer.colors(30, c( "blue","lightblue", "pink"  ,"red") )


persp(grid.a, grid.b, mean.fit, theta=30, phi=60)
image(grid.a, grid.b, mean.fit, col = colorTable)
timeElapsed

image.plot(grid.a, grid.b, mean.fit, col = colorTable)
#mean.fit

#Do not allow for negatives
h <- mean.fit
noZeroFit <- ifelse(h < 0, 0, h)


png(file="DonovanMitchell.png",width=500, height=360)
image.plot(grid.a, grid.b, noZeroFit, col = colorTable, main="Donavon Mitchell", sub="FG%: 45.3%, FG3%: 36.4, eFG%: 51.7", xlab="2019-2020 Stats:", ylab="")
dev.off()



persp(grid.a, grid.b, noZeroFit, theta=30, phi=60)


image.plot(grid.a, grid.b, mean.fit, col = colorTable)


```

```{r}
#From when player was in
p1 <- mean.fit
#From when player was out
p2 <- mean.fit
checkVal<- sum(abs(p1 - p2))
checkVal

```
5.321665


#Randomization Test

```{r}

#Get the full dataset back
gameData <- read.csv("~/Desktop/Thesis/ThesisBasketball/totalSunsGames.csv")
gameData <- gameData %>% filter(gameData$point != 1, gameData$shootingTeam != "PHX")

gameData <- gameData %>% filter(gameData$shootingTeam != "PHX")
gameData$playerDefending <- NULL
defendingPlayer <- "5958"


gameData$playerDefending <- ifelse((gameData$shootingTeam != "PHX" &
                                 (gameData$H1 == defendingPlayer | 
                                  gameData$H2 == defendingPlayer |
                                  gameData$H3 == defendingPlayer |
                                  gameData$H4 == defendingPlayer |
                                  gameData$H5 == defendingPlayer |
                                  gameData$A1 == defendingPlayer |
                                  gameData$A2 == defendingPlayer |
                                  gameData$A3 == defendingPlayer |
                                  gameData$A4 == defendingPlayer |
                                  gameData$A5 == defendingPlayer)), TRUE, FALSE)

gameData$pointsPerShot <- NULL
gameData$X_LOC <- NULL
gameData$Y_LOC <- NULL

for(i in 1:nrow(gameData)){
  gameData$X_LOC[i] <- -1 * as.double(gameData$baseline[i] * 500)
  gameData$Y_LOC[i] <- as.double(gameData$sideline[i] * 940)
  gameData$pointsPerShot[i] <- as.double(gameData$makes[i] * gameData$point[i])
}
#If you just want shots at the basket
gameData <- gameData %>% filter(gameData$X_LOC >= -50, gameData$X_LOC <= 50, gameData$Y_LOC <= 50, gameData$Y_LOC >= -11)

grid.a <- sort(unique(gameData$X_LOC))
grid.b <- sort(unique(gameData$Y_LOC))

  
  playerIn <- gameData %>% filter(gameData$playerDefending == TRUE)
  playerOut <- gameData %>% filter(gameData$playerDefending == FALSE)
  
  #Restructure SAMPLE1
  #The following code is so that we can get n, ppsAve for each location
  nvalues <- playerIn %>% group_by(X_LOC, Y_LOC) %>% count() 
  dupShots <- playerIn %>% left_join(nvalues)

  sumShots <- dupShots %>% group_by(X_LOC, Y_LOC) %>% mutate(pps = sum(pointsPerShot))

  #Now you have the pps for each location
  playerIn$n <- sumShots$n
  playerIn$ppsAve <- sumShots$pps/sumShots$n

  playerIn <- playerIn %>% arrange(X_LOC, Y_LOC)
  playerIn <- playerIn %>% distinct(X_LOC, Y_LOC, .keep_all = TRUE) %>% arrange(X_LOC, Y_LOC)
  
  
  #Restructure SAMPLE2
  #The following code is so that we can get n, ppsAve for each location
  nvalues1 <- playerOut %>% group_by(X_LOC, Y_LOC) %>% count() 
  dupShots1 <- playerOut %>% left_join(nvalues1)

  sumShots1 <- dupShots1 %>% group_by(X_LOC, Y_LOC) %>% mutate(pps = sum(pointsPerShot))

  #Now you have the pps for each location
  playerOut$n <- sumShots1$n
  playerOut$ppsAve <- sumShots1$pps/sumShots1$n

  playerOut <- playerOut %>% arrange(X_LOC, Y_LOC)
  playerOut <- playerOut %>% distinct(X_LOC, Y_LOC, .keep_all = TRUE) %>% arrange(X_LOC, Y_LOC)
  
  
  a <- covGen(grid.a, grid.b, lam = 47)
  
  #First sample
  b1 <- yVals(grid.a, grid.b, playerIn)
  c1 <- finalFunction(a, b1$tempY, b1$tempSig)
  k <- 1
  mean.fit1 <- matrix(0, nrow = length(grid.a), ncol = length(grid.b))
    for (i in 1:length(grid.a)) {
      for (j in 1:length(grid.b)) {
        mean.fit1[i, j] <- c1$mean[k]
        k <- k + 1
      }
    }
  #Second Sample
  b2 <- yVals(grid.a, grid.b, playerOut)
  c2 <- finalFunction(a, b2$tempY, b2$tempSig)
  k <- 1
  mean.fit2 <- matrix(0, nrow = length(grid.a), ncol = length(grid.b))
    for (i in 1:length(grid.a)) {
      for (j in 1:length(grid.b)) {
        mean.fit2[i, j] <- c2$mean[k]
        k <- k + 1
      }
    }

  value <- sum((mean.fit1 - mean.fit2))

  value
```

Ayton: 5.321665







```{r}
#Get the full dataset back
gameData <- read.csv("~/Desktop/Thesis/ThesisBasketball/totalSunsGames.csv")
gameData <- gameData %>% filter(gameData$point != 1, gameData$shootingTeam != "PHX")
gameData$pointsPerShot <- NULL
gameData$X_LOC <- NULL
gameData$Y_LOC <- NULL

for(i in 1:nrow(gameData)){
  gameData$X_LOC[i] <- -1 * as.double(gameData$baseline[i] * 500)
  gameData$Y_LOC[i] <- as.double(gameData$sideline[i] * 940)
  gameData$pointsPerShot[i] <- as.double(gameData$makes[i] * gameData$point[i])
}
#If you just want shots at the basket
gameData <- gameData %>% filter(gameData$X_LOC >= -50, gameData$X_LOC <= 50, gameData$Y_LOC <= 50, gameData$Y_LOC >= -11)

grid.a <- sort(unique(gameData$X_LOC))
grid.b <- sort(unique(gameData$Y_LOC))

nrow(gameData)


store <- c()
reps <- 1000

for(i in 1:reps){
  x <- sample_n(gameData, size = nrow(gameData))
  
  sample1 <- x[1:949,]
  sample2 <- x[950: 2067,]
  
  #Restructure SAMPLE1
  #The following code is so that we can get n, ppsAve for each location
  nvalues <- sample1 %>% group_by(X_LOC, Y_LOC) %>% count() 
  dupShots <- sample1 %>% left_join(nvalues)

  sumShots <- dupShots %>% group_by(X_LOC, Y_LOC) %>% mutate(pps = sum(pointsPerShot))

  #Now you have the pps for each location
  sample1$n <- sumShots$n
  sample1$ppsAve <- sumShots$pps/sumShots$n

  sample1 <- sample1 %>% arrange(X_LOC, Y_LOC)
  sample1 <- sample1 %>% distinct(X_LOC, Y_LOC, .keep_all = TRUE) %>% arrange(X_LOC, Y_LOC)
  
  
  #Restructure SAMPLE2
  #The following code is so that we can get n, ppsAve for each location
  nvalues1 <- sample2 %>% group_by(X_LOC, Y_LOC) %>% count() 
  dupShots1 <- sample2 %>% left_join(nvalues1)

  sumShots1 <- dupShots1 %>% group_by(X_LOC, Y_LOC) %>% mutate(pps = sum(pointsPerShot))

  #Now you have the pps for each location
  sample2$n <- sumShots1$n
  sample2$ppsAve <- sumShots1$pps/sumShots1$n

  sample2 <- sample2 %>% arrange(X_LOC, Y_LOC)
  sample2 <- sample2 %>% distinct(X_LOC, Y_LOC, .keep_all = TRUE) %>% arrange(X_LOC, Y_LOC)
  
  
  
  #a <- covGen(grid.a, grid.b, lam = 47)
  
  #First sample
  b1 <- yVals(grid.a, grid.b, sample1)
  c1 <- finalFunction(a, b1$tempY, b1$tempSig)
  k <- 1
  mean.fit1 <- matrix(0, nrow = length(grid.a), ncol = length(grid.b))
    for (i in 1:length(grid.a)) {
      for (j in 1:length(grid.b)) {
        mean.fit1[i, j] <- c1$mean[k]
        k <- k + 1
      }
    }
  #Second Sample
  b2 <- yVals(grid.a, grid.b, sample2)
  c2 <- finalFunction(a, b2$tempY, b2$tempSig)
  k <- 1
  mean.fit2 <- matrix(0, nrow = length(grid.a), ncol = length(grid.b))
    for (i in 1:length(grid.a)) {
      for (j in 1:length(grid.b)) {
        mean.fit2[i, j] <- c2$mean[k]
        k <- k + 1
      }
    }

  value <- sum((mean.fit1 - mean.fit2))
  store <- c(store, value)
  
}


mean(store > checkVal)


```






