---
title: "Thesis"
author: "Adam Rees"
date: "October 6, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rvest)
library(dplyr)
require(XML)
require(RCurl)
require(stringr)
require(png)
library(XML)

library(sp)
library(gstat)

#install.packages('rapportools')
library(rapportools)

```


Getting the original data up. Pull in what URL you want and work from there
```{r}

#Raps Vs Cavs 1/31 URL
#url <- getURL("https://sports.yahoo.com/nba/toronto-raptors-cleveland-cavaliers-2020013005/?section=gamestream")


#url <- getURL("https://sports.yahoo.com/nba/charlotte-hornets-washington-wizards-2020013027/?section=gamestream")


url <- getURL("https://sports.yahoo.com/nba/philadelphia-76ers-atlanta-hawks-2020013001/")

#Character where JUMPBALL happened
postJump <- gregexpr("JUMPBALL", url)
#the string before the JUMPBALL - needed to get the starters
starterStuff <- substr(url, 1, postJump[[1]][1])
players <- gregexpr("on_court", starterStuff)
playerIDs <- c()
starters <- c()

for(i in 1:length(players[[1]])){

#get all of the players IDS
playerIDs[i] <- substr(starterStuff, players[[1]][i] - 7, players[[1]][i] -4)

checkStarter <- substr(starterStuff, players[[1]][i] + 23, players[[1]][i] + 23)

#Identify if they are a starter or not
if(grepl(checkStarter, "0")){
  starters[i] <- FALSE 
  } else{
  starters[i] <- TRUE
}
}


startingLineups <- data.frame(playerIDs, starters)
justStarters <- startingLineups %>% filter(starters == TRUE)
startingIDs <- c()
for(i in 1:nrow(justStarters)){
  startingIDs[i] <- toString(justStarters$playerIDs[i])
}
startingIDs[11] <- "NULL"
startingIDs

#We only want the data after the jump for the gameStream
data <- substr(url, postJump[[1]], nchar(url))
```


```{r}

#Get all of the characters where shots were taken
shots <- gregexpr("SHOT", data)


newShots <- shots[[1]]
subs <- gregexpr("SUB", data)


#get rid of the NAs
newShots <- newShots[!is.na(newShots)]

#all of the characters where player is mentioned (could be for anything)
player <- gregexpr("player", data)
shotChar <- c()

#Match the player to the shooter
for (i in 1:length(newShots)){
  shotChar[i] <- player[[1]][which(player[[1]] > newShots[i] & player[[1]] < newShots[i]+47)]
}


shooterID <- c()
for(i in 1:length(shotChar)){
  shooterID[i] <- substr(data,shotChar[i]+9,shotChar[i]+12)
}

#data frame with every single shot and who shot it
shotAndShooter <- tibble(shotChar, shooterID)

#you can add a filter here
shotLocations <- shotAndShooter
```



Build a dataset for all of the subs
```{r}
subChars <- append(0,subs[[1]])
allSubs <- data.frame(subChars)
numSubs <- length(allSubs[[1]])

for(i in 1:numSubs){

  if(i == 1){
    allSubs$H1[1]<- startingIDs[1]
    allSubs$H2[1]<- startingIDs[2]
    allSubs$H3[1]<- startingIDs[3]
    allSubs$H4[1]<- startingIDs[4]
    allSubs$H5[1]<- startingIDs[5]
    allSubs$A1[1]<- startingIDs[6]
    allSubs$A2[1]<- startingIDs[7]
    allSubs$A3[1]<- startingIDs[8]
    allSubs$A4[1]<- startingIDs[9]
    allSubs$A5[1]<- startingIDs[10]
    allSubs$ExtraSub[1]<- startingIDs[11]

  }
  else{
  
    
    
    #find the players that are getting subbed in and subbed out
findPlayer <- substr(data, allSubs$subChars[i], allSubs$subChars[i] + 150)
findPlayer
playerEnter <- gregexpr("enter_player", findPlayer)
playerLeave <- gregexpr("leave_player", findPlayer)

enterPlayer <- substr(findPlayer, playerEnter[[1]] + 15, playerEnter[[1]] + 18)
leavePlayer <- substr(findPlayer, playerLeave[[1]] + 15, playerLeave[[1]] + 18)
    
    if(allSubs$H1[i-1] == leavePlayer){
      allSubs$H1[i] <- enterPlayer
    }else{
      allSubs$H1[i] <- allSubs$H1[i-1]
    }
    if(allSubs$H2[i-1] == leavePlayer){
      allSubs$H2[i] <- enterPlayer
    }else{
      allSubs$H2[i] <- allSubs$H2[i-1]
    }
    if(allSubs$H3[i-1] == leavePlayer){
      allSubs$H3[i] <- enterPlayer
    }else{
      allSubs$H3[i] <- allSubs$H3[i-1]
    }
    if(allSubs$H4[i-1] == leavePlayer){
      allSubs$H4[i] <- enterPlayer
    }else{
      allSubs$H4[i] <- allSubs$H4[i-1]
    }
    if(allSubs$H5[i-1] == leavePlayer){
      allSubs$H5[i] <- enterPlayer
    }else{
      allSubs$H5[i] <- allSubs$H5[i-1]
    }
    if(allSubs$A1[i-1] == leavePlayer){
      allSubs$A1[i] <- enterPlayer
    }else{
      allSubs$A1[i] <- allSubs$A1[i-1]
    }
    if(allSubs$A2[i-1] == leavePlayer){
      allSubs$A2[i] <- enterPlayer
    }else{
    allSubs$A2[i] <- allSubs$A2[i-1]
    }
    if(allSubs$A3[i-1] == leavePlayer){
      allSubs$A3[i] <- enterPlayer
    }else{
      allSubs$A3[i] <- allSubs$A3[i-1]
    }
    if(allSubs$A4[i-1] == leavePlayer){
      allSubs$A4[i] <- enterPlayer
    }else{
      allSubs$A4[i] <- allSubs$A4[i-1]
    }
    if(allSubs$A5[i-1] == leavePlayer){
      allSubs$A5[i] <- enterPlayer
    }else{
      allSubs$A5[i] <- allSubs$A5[i-1]
    }
    if(allSubs$H1[i-1] != leavePlayer & allSubs$H2[i-1] != leavePlayer & allSubs$H3[i-1] != leavePlayer & allSubs$H4[i-1] != leavePlayer & allSubs$H5[i-1] != leavePlayer & allSubs$A1[i-1] != leavePlayer & allSubs$A2[i-1] != leavePlayer & allSubs$A3[i-1] != leavePlayer & allSubs$A4[i-1] != leavePlayer & allSubs$A5[i-1] != leavePlayer){
    allSubs$ExtraSub[i] <- enterPlayer}
    else{
    allSubs$ExtraSub[i] <- allSubs$ExtraSub[i-1]

    }
    
}
    
  
  }
```




Currently: getting NAs on the enter player and leave player. need to get the leave and enter player better like grab the whole string and work from there
```{r}

    

#number of shots taken in the game
numShots <- nrow(shotLocations)


for(i in 1:numShots){


fullString <- substr(data, shotLocations$shotChar[i], shotLocations$shotChar[i] + 450)

timeChr <- gregexpr("clock", fullString)
findTime <- substr(fullString, timeChr[[1]]+8, timeChr[[1]] + 12)

if(!substr(findTime, 1, 1) == "1" | substr(findTime, 1, 2) == "1:"){
  findTime <- substr(findTime, 1, 4)
}
if(substr(findTime, 1, 1) == ":"){
  findTime <- paste("0", substr(findTime, 1, 3), sep = "") 
}

shotLocations$Time[i] <- findTime

periodString <- substr(data, shotLocations$shotChar[i]-50, shotLocations$shotChar[i])
periodChr <- gregexpr("period", periodString)
findPeriod <- substr(periodString, periodChr[[1]]+9, periodChr[[1]] + 9)

shotLocations$Period[i] <- findPeriod


# Find the score for the home team
homescoreChr <- gregexpr("home_score", fullString)
findHomeScore <- substr(fullString, homescoreChr[[1]]+13, homescoreChr[[1]] + 15)
if(grepl(",", findHomeScore)){
  findComma <- gregexpr(",", findHomeScore)
  findHomeScore <- substr(findHomeScore, 1, findComma[[1]] - 2)
}
x <- substr(findHomeScore, 3, 3)
if(is.na(as.numeric(x)) & !is.empty(x)){
  findHomeScore <- substr(findHomeScore, 1, 2)
}

shotLocations$HomeScore[i] <- findHomeScore

fStr <- substr(data, shotLocations$shotChar[i] - 25, shotLocations$shotChar[i])

awayScoreChr <- gregexpr("away_score", fStr)
findAwayScore <- substr(fStr, awayScoreChr[[1]] + 13, awayScoreChr[[1]] + 18)

if(grepl(",", findAwayScore)){
  findComma <- gregexpr(",", findAwayScore)
  findAwayScore <- substr(findAwayScore, 1, findComma[[1]] - 2)
}

shotLocations$AwayScore[i] <- findAwayScore

    
#Find the baseline offset by getting a large string after the shot, finding where it says baseline offset and taking the number after it
findBaseline <- substr(data, shotLocations$shotChar[i], shotLocations$shotChar[i] + 120)
charBaseline <- gregexpr("baseline_offset", findBaseline)
baseString <- substr(findBaseline, charBaseline[[1]] + 28, charBaseline[[1]] + 34)

#baseline offset could be 0 to 4 characters - we want to just grab the number
if(grepl(",", baseString)){
  findComma <- gregexpr(",", baseString)
  baseString <- substr(baseString, 1, findComma[[1]] - 1)
}

#Same code but now for sideline offset
findSideline <- substr(data, shotLocations$shotChar[i], shotLocations$shotChar[i] + 300)
charSideline <- gregexpr("sideline_offset", findSideline)
sideString <- substr(findSideline, charSideline[[1]] + 28, charSideline[[1]] + 33)

if(grepl(",", sideString)){
 findComma <- gregexpr(",", sideString)
 sideString <- substr(sideString, 1, findComma[[1]] - 1)
}
 
#they were characters but we want it to be a double
shotLocations$baselineOffset[i] <- as.numeric(baseString)
shotLocations$sidelineOffset[i] <- as.numeric(sideString)

#find if the shot was made or missed
findMakeMiss <- substr(data, shotLocations$shotChar[i], shotLocations$shotChar[i] + 460)
makeMiss <- gregexpr("shot_made", findMakeMiss)
makeMiss <- substr(findMakeMiss, makeMiss[[1]] + 12, makeMiss[[1]] + 12)

#find if the shot was a 3 or a 2
shotType <- gregexpr("points", findMakeMiss)
shotType <- substr(findMakeMiss, shotType[[1]] + 9, shotType[[1]] + 9)
shotLocations$shotType[i] <- as.double(shotType)

#find what team the player was on
findTeam <- substr(data, shotLocations$shotChar[i], shotLocations$shotChar[i] + 460)
teamCharacter <- gregexpr("team", findTeam)
team <- substr(findTeam, teamCharacter[[1]] + 7, teamCharacter[[1]] + 8)

if(is.na(as.numeric(team))){
 team <- substr(team, 1, 1)
}

shotLocations$Team[i] <- team

if(makeMiss == "1"){
  shotLocations$MakeMiss[i] <- 1
} else{
  shotLocations$MakeMiss[i] <- 0
}

#we now need to find what side of the basket the shot was taken. This is needed because the baseline offset is the same number for different sides of the basket
shotLocations$sideBasket[i] <- substr(data, shotLocations$shotChar[i] + 62, shotLocations$shotChar[i] + 62)

#use this to create a new variable plotting the X Location
if(shotLocations$sideBasket[i] == 'R'){
  shotLocations$X_LOC[i] <- as.double(shotLocations$baselineOffset[i] * 500)
} else{
  shotLocations$X_LOC[i] <- as.double(-1 * shotLocations$baselineOffset[i] * 500)
}

#also want the y location
shotLocations$Y_LOC[i] <- shotLocations$sidelineOffset[i] * 850

}

#get the home and away teams
teams <- unique(shotLocations$Team)
#set the opposing team
shotLocations$OpposingTeam <- ifelse(shotLocations$Team == teams[1], teams[2], teams[1])


#even after the for loop some X vals where characters - make sure they are doubles
shotLocations$X_LOC <- as.double(shotLocations$X_LOC)




#Filter out Free Throws
shotsNoFT <- shotLocations %>% filter(!(shotLocations$sidelineOffset == 0.1573 & shotLocations$baselineOffset == 0.00))


#coordinates(shotsNoFT) <- ~X_LOC + Y_LOC
makes <- shotsNoFT %>% filter(shotsNoFT$MakeMiss == 1)
misses <- shotsNoFT %>% filter(shotsNoFT$MakeMiss == 0)


coordinates(makes) <- ~X_LOC + Y_LOC
coordinates(misses) <- ~X_LOC + Y_LOC

plot(makes, pch = 1)
points(misses, pch = 4)

    shotsNoFT$H1<- ""
    shotsNoFT$H2<- ""
    shotsNoFT$H3<- ""
    shotsNoFT$H4<- ""
    shotsNoFT$H5<- ""
    shotsNoFT$A1<- ""
    shotsNoFT$A2<- ""
    shotsNoFT$A3<- ""
    shotsNoFT$A4<- ""
    shotsNoFT$A5<- ""

 currentLineUp <- 1
 maxSub <- length(allSubs[[1]])
 maxShot <- length(shotsNoFT[[1]])
 
for(i in 1:maxShot){
  #first, find what index of the subs players you want to use
  while(currentLineUp < maxSub & shotsNoFT$shotChar[i] > allSubs$subChars[currentLineUp + 1]){
    currentLineUp <- currentLineUp + 1
  }
  
  
  #update shotsNoFT to that index
    shotsNoFT$H1[i]<- allSubs$H1[currentLineUp]
    shotsNoFT$H2[i]<- allSubs$H2[currentLineUp]
    shotsNoFT$H3[i]<- allSubs$H3[currentLineUp]
    shotsNoFT$H4[i]<- allSubs$H4[currentLineUp]
    shotsNoFT$H5[i]<- allSubs$H5[currentLineUp]
    shotsNoFT$A1[i]<- allSubs$A1[currentLineUp]
    shotsNoFT$A2[i]<- allSubs$A2[currentLineUp]
    shotsNoFT$A3[i]<- allSubs$A3[currentLineUp]
    shotsNoFT$A4[i]<- allSubs$A4[currentLineUp]
    shotsNoFT$A5[i]<- allSubs$A5[currentLineUp]
    shotsNoFT$ExtraSub[i]<- allSubs$ExtraSub[currentLineUp]


}
 
 
sixersVhawks <- shotsNoFT





```

```{r}


#Need to build two datasets, one with Player X on the court and one without
playerX <- "6163"
xInGame <- finalShots %>% filter(H1 == playerX | H2 == playerX | H3 == playerX | H4 == playerX | H5 == playerX)
xInGame
```

```{r}
fullData <- rbind(rapsVcavs, hornetsVwiz, sixersVhawks)

oneQuarter <- filter(fullData, Period == "3")
otherQ <- filter(fullData, Period != "3")
shotsInQTR <- nrow(oneQuarter)

#need to make sure there is equal spacing
oneQ <- kde2d(oneQuarter$X_LOC, oneQuarter$Y_LOC, lims = c(-250, 250, -20, 375))

otherQs <- kde2d(otherQ$X_LOC, otherQ$Y_LOC, lims = c(-250, 250, -20, 375))


checkVal<- sum(abs(oneQ$z - otherQs$z))



store <- c()
reps <- 1000


for(i in 1:reps){
  x <- sample_n(fullData, size = nrow(fullData))
  a <- x[1:123,]
  b <- x[124:528,]
  
  randomOne <- kde2d(a$X_LOC, a$Y_LOC, lims = c(-250, 250, -20, 375))
  randomTwo <- kde2d(b$X_LOC, b$Y_LOC, lims = c(-250, 250, -20, 375))
  
  value <- sum(abs(randomOne$z - randomTwo$z))
  store <- c(store, value)
  
}


mean(store > checkVal)

```

```{r}
persp(oneQ, theta = 0, phi = 55)
persp(otherQs)
```






